# GitHub Action for running 
name: PyTest
on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 12 * * SUN'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          python setup.py develop
          pytest tests/